// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDD-t6ht9JCnl-FtOp8m31zzbv4tXFozJY',
    appId: '1:94987259147:web:e61b9287bc83073682660e',
    messagingSenderId: '94987259147',
    projectId: 'serphanid',
    authDomain: 'serphanid.firebaseapp.com',
    databaseURL: 'https://serphanid-default-rtdb.firebaseio.com',
    storageBucket: 'serphanid.appspot.com',
    measurementId: 'G-R5G7VVGCP5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC70dHUssFSLATF7nV2OEAhDCftc-Hhf4A',
    appId: '1:94987259147:android:4e5b2734bc5cd94282660e',
    messagingSenderId: '94987259147',
    projectId: 'serphanid',
    databaseURL: 'https://serphanid-default-rtdb.firebaseio.com',
    storageBucket: 'serphanid.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCdRNsEWCmvwJlk7jJ2jwc-DpGzaw6wXhg',
    appId: '1:94987259147:ios:de44c977ac5e946f82660e',
    messagingSenderId: '94987259147',
    projectId: 'serphanid',
    databaseURL: 'https://serphanid-default-rtdb.firebaseio.com',
    storageBucket: 'serphanid.appspot.com',
    androidClientId: '94987259147-6kcpa0b4sal6v0t1c59smmut46igdac9.apps.googleusercontent.com',
    iosBundleId: 'com.example.serphantsid',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCdRNsEWCmvwJlk7jJ2jwc-DpGzaw6wXhg',
    appId: '1:94987259147:ios:a56510e205a53a3582660e',
    messagingSenderId: '94987259147',
    projectId: 'serphanid',
    databaseURL: 'https://serphanid-default-rtdb.firebaseio.com',
    storageBucket: 'serphanid.appspot.com',
    androidClientId: '94987259147-6kcpa0b4sal6v0t1c59smmut46igdac9.apps.googleusercontent.com',
    iosBundleId: 'com.example.serphantsid.RunnerTests',
  );
}
